### PR TITLE
Table for Interest Rates

### PR DESCRIPTION
**Pull request by martinkrung**
Now there is a table, which helps to compare different curves and can be pasted into a sheet. 

Maybe position on the table  could be nicer?  What do you think @saint-rat?

Preview here:

https://curve-resources-b9m0fcoq5-curvedocs.vercel.app/lending/create-lending-market/#borrowing-interest-rates

### CODE REVIEW

**Comment by mo-anon** [comment]
too much info imo

**Comment by martinkrung** [comment]
disagree, it's what I need in my daily work.  And others may too.  

The curve itself looks nice, but is close to useless. What I do is set different rates, than copy past the values and compare between different settings.  now many markets have not ideal setting because what matters is the rate between 70-90 and most markets are too high which results in low capital efficiency.

**Comment by saint-rat** [comment]
Yeah I'm personally with Mo here, I had something similar in an earlier draft for this page but me and Mo decided to leave it just as the chart.

**Comment by saint-rat** [comment]
Could have it under a collapsable heading to keep the page look clean but also have the table for those who need it?

**Comment by saint-rat** [comment]
Merged this change as a collapsible table.

**Pull request merged**
